---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-demo
  namespace: dev
  annotations:
    flux.weave.works/tag.podinfod: glob:*
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Performing risky op"'
    flux.weave.works/locked_user: Ilya Dmitrichenko <ilya@weave.works>
spec:
  replicas: 4
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metrics-demo
        image: quay.io/brice/metrics-demo
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

